wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1671638771.849887
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.13.5
      8:
      - 5
aggregate:
  desc: null
  value: uniform
algo_para:
  desc: null
  value: null
algorithm:
  desc: null
  value: fedalgo1
batch_size:
  desc: null
  value: 32.0
bins:
  desc: null
  value: 1000
cross_validation:
  desc: null
  value: false
early_stop:
  desc: null
  value: -1
eval_interval:
  desc: null
  value: 1
gpu:
  desc: null
  value: null
group_name:
  desc: null
  value: NIID_10client
idx_path:
  desc: null
  value: Dataset_scenarios/NIID_10clients_random.json
learning_rate:
  desc: null
  value: 0.01
learning_rate_decay:
  desc: null
  value: 0.998
log_file:
  desc: null
  value: false
log_interval:
  desc: null
  value: 1
log_level:
  desc: null
  value: INFO
log_result_path:
  desc: null
  value: Saved_Results
log_wandb:
  desc: null
  value: true
logger:
  desc: null
  value: basic_logger
lr_scheduler:
  desc: null
  value: -1
model:
  desc: null
  value: resnet18
momentum:
  desc: null
  value: 0.9
no_log_console:
  desc: null
  value: false
no_overwrite:
  desc: null
  value: false
num_classes:
  desc: null
  value: 77
num_epochs:
  desc: null
  value: 5
num_rounds:
  desc: null
  value: 200
num_steps:
  desc: null
  value: -1
num_workers:
  desc: null
  value: 0
optimizer:
  desc: null
  value: SGD
proportion:
  desc: null
  value: 0.5
ratio:
  desc: null
  value: 0.6
sample:
  desc: null
  value: uniform
sampler:
  desc: null
  value: threshold_sampler
score:
  desc: null
  value: all_gnorm_threshold
seed:
  desc: null
  value: 0
server_with_cpu:
  desc: null
  value: false
session_name:
  desc: null
  value: fedalgo1_ratio_0.6_C_0.5_
task:
  desc: null
  value: pill_classification
test_batch_size:
  desc: null
  value: 512
threshold:
  desc: null
  value: 0
train_on_all:
  desc: null
  value: false
use_pretrained:
  desc: null
  value: true
use_sampler:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 0
